redir-port: 9797
tproxy-port: 9898
mode: rule
allow-lan: true
bind-address: "*"
log-level: silent
ipv6: false
external-controller: 0.0.0.0:9090
secret: "114514"
external-ui: /data/adb/box/clash/dashboard

profile:
  store-selected: true
  store-fake-ip: false

tun:
  exclude-package: []
  enable: false
  device: utun
  mtu: 9000
  stack: system
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  ipv6: true
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
  listen: 0.0.0.0:1053
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
  nameserver:
    - 8.8.8.8
    - 1.0.0.1

